# -*- coding: utf-8 -*-
"""regression linéaire.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6vKJ3zZKQfY1nMih8YEFCPQLIVQRjNj
"""

import numpy as np 
import pandas as pd 
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

data=pd.read_csv('qualifying.csv')
data

new_data=data.drop(columns=['qualifyId','q1','q2','q3','number'])
new_data

x=new_data.iloc[:,:-1]
y=new_data.iloc[:,-1]
y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1.0/3,random_state=100)

regressor=LinearRegression()

regressor.fit(x_train,y_train)

regressor.coef_

regressor.intercept_

regressor.predict([[1060,853,210]])